# Generated by Django 3.0.8 on 2020-09-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_imagetaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetaker',
            name='image',
            field=models.ImageField(upload_to='Facepics/%Y/%m/%d'),
        ),
    ]
